if (!identical(Sys.getenv("DELPHYR_TEST_DB"), "true")) stop("Set DELPHYR_TEST_DB=true to opt in.")
b<-chromote::ChromoteSession$new();b$Page$navigate('http://127.0.0.1:3868');Sys.sleep(2)
js<-function(code){r<-b$Runtime$evaluate(code);if(!is.null(r$exceptionDetails))stop(r$exceptionDetails$text);r$result$value}
key<-function(key,code,number){b$Input$dispatchKeyEvent(type='keyDown',key=key,code=code,windowsVirtualKeyCode=number,text=if(key=='Enter') '\r' else if(key==' ') ' ' else '');b$Input$dispatchKeyEvent(type='keyUp',key=key,code=code,windowsVirtualKeyCode=number)}
focus<-function(id)js(sprintf("document.getElementById('%s').focus()",id))
select_text<-function(id,text){js(sprintf("document.getElementById('%s').selectize.focus()",id));b$Input$insertText(text=text);Sys.sleep(.2);key('Enter','Enter',13);Sys.sleep(.3)}
focus('panel-load');key('Enter','Enter',13);Sys.sleep(.6)
focus('panel-consent_check');key(' ','Space',32);key('Tab','Tab',9);key('Enter','Enter',13);Sys.sleep(.4)
select_text('panel-item_1_1-kind','Give a response');select_text('panel-item_1_1-value','7')
x<-js("JSON.stringify({kind:document.getElementById('panel-item_1_1-kind').value,value:document.getElementById('panel-item_1_1-value').value})");print(x);stopifnot(length(x)==1,grepl('"kind":"answered"',x,fixed=TRUE),grepl('"value":"7"',x,fixed=TRUE))
focus('panel-item_1_1-save');key('Enter','Enter',13);Sys.sleep(.4)
x<-js("document.getElementById('panel-item_1_1-status').innerText");print(x);stopifnot(length(x)==1,grepl('Saved:',x,fixed=TRUE))
select_text('panel-item_1_1-value','8')
x<-js("document.getElementById('panel-item_1_1-status').innerText");print(x);stopifnot(length(x)==1,grepl('Unsaved change',x,fixed=TRUE),!grepl('Saved:',x,fixed=TRUE))
b$Network$enable();b$Network$emulateNetworkConditions(offline=TRUE,latency=0,downloadThroughput=0,uploadThroughput=0)
js("Shiny.shinyapp.$socket.close()")
Sys.sleep(.4)
x<-js("document.getElementById('panel-connection').innerText");print(x);stopifnot(length(x)==1,grepl('Connection lost. Changes are not being saved.',x,fixed=TRUE))
stopifnot(isTRUE(js("document.getElementById('panel-item_1_1-status').parentElement.hidden")))
focus('panel-item_1_1-save');key('Enter','Enter',13)
b$screenshot(file.path(tempdir(),'delphyr-network-disconnected.png'))
b$Network$emulateNetworkConditions(offline=FALSE,latency=0,downloadThroughput=-1,uploadThroughput=-1);b$Page$reload();Sys.sleep(2)
focus('panel-load');key('Enter','Enter',13);Sys.sleep(.5)
x<-js("document.getElementById('panel-item_1_1-value').value");print(x);stopifnot(identical(x,'7'))
labels<-js("JSON.stringify(Array.from(document.querySelectorAll('input,select,textarea')).filter(e=>e.offsetWidth>0&&e.type!=='hidden').map(e=>({id:e.id,label:!!document.querySelector('label[for=\"'+e.id+'\"]')||!!e.closest('label')||!!e.getAttribute('aria-label')||!!e.getAttribute('aria-labelledby')})))")
print(labels);stopifnot(!grepl('"label":false',labels,fixed=TRUE))
focus('panel-confirm');key(' ','Space',32);key('Tab','Tab',9);key('Enter','Enter',13);Sys.sleep(.5)
x<-js("document.getElementById('panel-receipt').innerText");print(x);stopifnot(length(x)==1,grepl('Submission confirmed:',x,fixed=TRUE))
b$Emulation$setDeviceMetricsOverride(width=390,height=844,deviceScaleFactor=1,mobile=TRUE)
x<-js("JSON.stringify({width:innerWidth,body:document.body.scrollWidth,editorial:!!document.getElementById('editorial-record'),campaign:!!document.getElementById('communications-prepare')})");print(x);stopifnot(grepl('"body":390',x,fixed=TRUE),grepl('"editorial":false',x,fixed=TRUE),grepl('"campaign":false',x,fixed=TRUE))
b$screenshot(file.path(tempdir(),'delphyr-keyboard-mobile.png'));b$close()
