if (!identical(Sys.getenv("DELPHYR_TEST_DB"), "true")) stop("Set DELPHYR_TEST_DB=true to opt in.")
b<-chromote::ChromoteSession$new();b$Page$navigate('http://127.0.0.1:3875');Sys.sleep(2)
js<-function(code){r<-b$Runtime$evaluate(code);if(!is.null(r$exceptionDetails))stop(r$exceptionDetails$text);r$result$value}
js("document.getElementById('language').selectize.setValue('en')");Sys.sleep(.4)
x<-js("document.getElementById('intro').innerText");print(x);stopifnot(length(x)==1,grepl('Manage the protocol',x,fixed=TRUE))
x<-js("JSON.stringify(Array.from(document.querySelectorAll('.del-nav a')).map(x=>({label:x.textContent,target:x.getAttribute('href')})))");print(x);stopifnot(length(x)==1,grepl('section-panel-import',x,fixed=TRUE),!grepl('My participation',x,fixed=TRUE))
# Every link is filtered by the rights of the account, leads to a section that exists and occurs once.
links<-jsonlite::fromJSON(x);stopifnot(nrow(links)>=5,!anyDuplicated(links$target),!'#section-panel'%in%links$target,isTRUE(js("Array.from(document.querySelectorAll('.del-nav a')).every(a=>document.querySelector(a.getAttribute('href'))!==null)")))
js("var e=document.getElementById('management-reason');e.value='Unsubmitted navigation check';e.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('.del-nav a[href=\"#section-panel-import\"]').click()")
stopifnot(identical(js('location.hash'),'#section-panel-import'))
js("document.querySelector('.del-nav a[href=\"#section-management\"]').click()")
stopifnot(identical(js("document.getElementById('management-reason').value"),'Unsubmitted navigation check'))
js('scrollTo(0,0)');b$Emulation$setDeviceMetricsOverride(width=390,height=844,deviceScaleFactor=1,mobile=TRUE);Sys.sleep(.3)
x<-js("JSON.stringify({width:innerWidth,body:document.body.scrollWidth,links:document.querySelectorAll('.del-nav a').length})");print(x);stopifnot(grepl('"body":390',x,fixed=TRUE),identical(jsonlite::fromJSON(x)$links,nrow(links)))
png<-b$Page$captureScreenshot(format='png',captureBeyondViewport=FALSE)$data;writeBin(jsonlite::base64_dec(png),file.path(tempdir(),'delphyr-manager-navigation-mobile.png'))
b$Emulation$setDeviceMetricsOverride(width=1280,height=900,deviceScaleFactor=1,mobile=FALSE);js('scrollTo(0,0)');Sys.sleep(.2)
png<-b$Page$captureScreenshot(format='png',captureBeyondViewport=FALSE)$data;writeBin(jsonlite::base64_dec(png),file.path(tempdir(),'delphyr-manager-navigation-desktop.png'))
b$close()
