if (!identical(Sys.getenv("DELPHYR_TEST_DB"), "true")) stop("Set DELPHYR_TEST_DB=true to opt in.")
.libPaths(c(normalizePath('.R-library'),.libPaths()));pkgload::load_all('packages/delphyr',quiet=TRUE)
f<-readRDS(Sys.getenv('DELPHYR_PROTOCOL_FIXTURE','.checks/protocol-browser-fixture.rds'))
r<-connect_repository(host='127.0.0.1',port=55439,dbname='delphyr',user='delphyr_runtime',environment='development',artifact_root=file.path(getwd(),'.artifacts'))
v<-list_protocol_versions(r,demo_actor(r,f$manager$principal_id),f$study_id)
panel<-demo_actor(r,f$panel[[1]]$principal_id);e<-list_enrollments(r,panel,f$study_id);q<-get_questionnaire(r,panel,e$id)
stopifnot(nrow(v)==2L,v$hash[v$version==1L]==f$original$hash,jsonlite::fromJSON(v$config[v$version==2L])$stopping$max_rounds==4L,q$protocol$stopping$max_rounds==3L)
print(list(protocol_versions=nrow(v),original_hash_preserved=TRUE,latest_max_rounds=4L,existing_round_max_rounds=q$protocol$stopping$max_rounds,amendment_reason=v$reason[v$version==2L]))
DBI::dbDisconnect(r$con)
