if (!identical(Sys.getenv("DELPHYR_TEST_DB"), "true")) stop("Set DELPHYR_TEST_DB=true to opt in.")
.libPaths(c(normalizePath('.R-library'),.libPaths()));pkgload::load_all('packages/delphyr',quiet=TRUE)
f<-readRDS(Sys.getenv('DELPHYR_EDITORIAL_FIXTURE','.checks/editorial-campaign-fixture.rds'))
r<-connect_repository(host='127.0.0.1',port=55439,dbname='delphyr',user='delphyr_runtime',environment='development',artifact_root=file.path(getwd(),'.artifacts'))
a<-demo_actor(r,f$manager$principal_id);p<-get_qualitative_provenance(r,a,f$study_id)
stopifnot(nrow(p$sources)==1,nrow(p$edits)==1,nrow(p$releases)==1,p$sources$original_text=='Synthetic original with a fictional identifier SAMPLE-12.',p$edits$kind=='summary',p$edits$redacted_text=='Synthetic summary without the fictional identifier.',p$releases$reviewer_id!=p$edits$edited_by)
w<-connect_repository(host='127.0.0.1',port=55439,dbname='delphyr',user='postgres',environment='development',artifact_root=file.path(getwd(),'.artifacts'))
id<-DBI::dbGetQuery(w$con,'SELECT id FROM ops.campaigns WHERE study_id=$1',params=list(f$study_id))$id
stopifnot(length(id)==1)
c<-preview_campaign(r,a,id);stopifnot(c$released,nrow(c$recipients)==1,c$subject=='Synthetic QA invitation')
result<-process_campaign_sink(w,study_id=f$study_id)
if(!identical(result,FALSE)) stopifnot(result$state=='sink_recorded')
c<-preview_campaign(r,a,id);stopifnot(c$recipients$delivery_state=='sink_recorded')
print(list(original_sources=nrow(p$sources),separate_edits=nrow(p$edits),independent_releases=nrow(p$releases),campaign_recipients=nrow(c$recipients),delivery_state=c$recipients$delivery_state,external_email=FALSE))
DBI::dbDisconnect(r$con);DBI::dbDisconnect(w$con)
