.libPaths(c(normalizePath(".R-library"), .libPaths()))
pkgload::load_all("packages/delphyr", quiet = TRUE)
r <- connect_repository(host = "127.0.0.1", port = 55439, dbname = "delphyr", user = "postgres", environment = "test", artifact_root = file.path(getwd(), ".artifacts"))
migrate_repository(r)
f <- demo_study(r, n = 4, item_count = 2)
for (st in c("review", "approved", "open")) transition_round(r, f$manager, f$round$id, st, f$round$hash, "Synthetic test", st)
a <- f$panel[[1]]
e <- list_enrollments(r, a, f$study_id)$id[1]
q <- get_questionnaire(r, a, e)
stopifnot(!q$consent$accepted)
record_consent(r, a, f$study_id, f$consent_id, TRUE, "consent")
for (it in q$items$id) save_response(r, a, e, it, list(value = 9L, status = "answered"), 0L, it)
q <- get_questionnaire(r, a, e)
sub <- submit_round(r, a, e, setNames(q$responses$revision, q$responses$round_item_id), "submit")
stopifnot(identical(sub, submit_round(r, a, e, setNames(q$responses$revision, q$responses$round_item_id), "submit")))
transition_round(r, f$manager, f$round$id, "closed", f$round$hash, "Test complete", "close")
s <- freeze_round(r, f$manager, f$round$id, "freeze")
x <- get_snapshot(r, f$manager, s$id)
a1 <- run_analysis(r, f$manager, s$id, "analyse")
f1 <- create_feedback(r, f$manager, a1$id, command_id = "feedback")
release_feedback(r, f$manager, f1$id, f1$hash, "release")
stopifnot(all(analyse_round(x)$results$n_valid <= 1))
cat("SERVICE SMOKE PASS\n")
DBI::dbDisconnect(r$con)
